[project]
name = "backend"
version = "0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastapi (>=0.115.12,<0.116.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
