apiVersion: v1
kind: Namespace
metadata:
  name: ${NAME}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  namespace: ${NAME}
  labels:
    app: ${NAME}
spec:
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ${IMAGE_URL}
          resources:
            limits:
              cpu: "500m"
              memory: "2048Mi"
          env:
            - name: PORT
              value: "80"
            - name: BSKY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-bsky
                  key: BSKY_USERNAME
            - name: BSKY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-bsky
                  key: BSKY_PASSWORD
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${NAME}-letsencrypt
  namespace: ${NAME}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            name: ${NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  namespace: ${NAME}
spec:
  selector:
    app: ${NAME}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${NAME}
  namespace: ${NAME}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ${NAME}
    cert-manager.io/issuer: ${NAME}-letsencrypt
spec:
  tls:
    - secretName: ${NAME}-cert
      hosts:
        - ${DNS_NAME}
  rules:
    - host: ${DNS_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${NAME}
                port:
                  number: 80

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${NAME}-secrets
  namespace: ${NAME}
spec:
  provider: gcp
  parameters:
    secrets:
      - resourceName: "projects/${PROJECT_ID}/secrets/${NAME}-bluesky-username/versions/latest"
        path: "BLUESKY_USERNAME"
      - resourceName: "projects/${PROJECT_ID}/secrets/${NAME}-bluesky-password/versions/latest"
        path: "BLUESKY_PASSWORD"
