apiVersion: v1
kind: Namespace
metadata:
  name: ${NAME}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  namespace: ${NAME}
  labels:
    app: ${NAME}
spec:
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ${IMAGE_URL}
          resources:
            limits:
              cpu: "500m"
              memory: "2048Mi"
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${NAME}-letsencrypt-staging
  namespace: ${NAME}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            name: ${NAME}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${NAME}
  namespace: ${NAME}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ${NAME}
    cert-manager.io/issuer: ${NAME}-letsencrypt-staging
spec:
  tls:
    - secretName: ${NAME}-cert
      hosts:
        - ${DNS_NAME}
  rules:
    - host: ${DNS_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${NAME}
                port:
                  number: 80
