name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ github.repository }}/providers/${{ github.repository }}"
          service_account: "coilysiren-backend@coilysiren-deploy.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud projects list
