name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "NAME_DASHED=$(make .name-dashed)" >> $GITHUB_ENV
      - uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/coilysiren-backend/providers/coilysiren-backend"
          service_account: "coilysiren-backend@coilysiren-deploy.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v2
      - run: make .build-docker
      - run: make .publish
