name: deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/coilysiren-backend/providers/coilysiren-backend"
          service_account: "coilysiren-backend@coilysiren-deploy.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v2
      - run: pulumi stack select build
      - run: name=coilysiren-backend make .build-docker
      - run: name=coilysiren-backend make .publish
